# Generated by Django 4.1.3 on 2024-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=99)),
                ('date', models.DateField()),
                ('max_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('min_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
