# Generated by Django 4.1.3 on 2024-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=99)),
                ('year', models.IntegerField()),
                ('avg_max_temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_min_temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_ppt', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
