# Generated by Django 4.1.3 on 2024-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatheranalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheranalytics',
            name='total_ppt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
